### ISSUE TITLE
Use train_and_evaluate() rather than learn_runner

### ISSUE THREAD

**Issue by lakshmanok** [GoogleCloudPlatform/training-data-analyst#122]
For example:

update 08_image/mnistmodel/trainer/task.py to use model.train_and_evaluate() instead of using learn_runner

**Comment by Bhavyabhushanyadav** [comment]
@lakshmanok this code https://github.com/GoogleCloudPlatform/training-data-analyst/blob/acb1ded9234ebc0ab2ae1f3163ff43d68083b14d/courses/machine_learning/deepdive/05_artandscience/d_customestimator.ipynb can not perform training on cloudml.

When you use train_and_evaluate function it throws error and training is not performed on cloud ML

I am able to run this code on local machine 

I have attached the screenshot of the error

{
 insertId:  "1aci8fzg6ycetxm"  
 jsonPayload: {
  created:  1521028818.325793   
  levelname:  "ERROR"   
  lineno:  345   
  message:  "2018-03-14 12:00:18.325605: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Attempted to repeat an empty dataset infinitely."   
  pathname:  "/runcloudml.py"   
 }
 labels: {
  compute.googleapis.com/resource_id:  "2790092095787191020"   
  compute.googleapis.com/resource_name:  "cmle-training-master-29e0961593-0-btrpt"   
  compute.googleapis.com/zone:  "us-central1-c"   
  ml.googleapis.com/job_id:  "plutots_180314_115915"   
  ml.googleapis.com/job_id/log_area:  "root"   
  ml.googleapis.com/task_name:  "master-replica-0"   
  ml.googleapis.com/trial_id:  ""   
 }
 logName:  "projects/newproject-186115/logs/master-replica-0"  
 receiveTimestamp:  "2018-03-14T12:00:40.702801781Z"  
 resource: {
  labels: {
   job_id:  "plutots_180314_115915"    
   project_id:  "newproject-186115"    
   task_name:  "master-replica-0"    
  }
  type:  "ml_job"   
 }
 severity:  "ERROR"  
 timestamp:  "2018-03-14T12:00:18.325793027Z"  
}

![image](https://user-images.githubusercontent.com/16779498/37460546-819e6da8-2871-11e8-9868-5e4e1e187fd6.png)
