### ISSUE TITLE
ImportError: cannot import name pywrap_tensorflow - deepdive/07_structured/4_preproc_tft.ipynb

### ISSUE THREAD

**Issue by andrewm4894** [GoogleCloudPlatform/training-data-analyst#133]
I got this error while running through this [codelab](https://codelabs.developers.google.com/codelabs/end-to-end-ml/index.html#5)

![image](https://user-images.githubusercontent.com/2178292/37207532-5ea1130e-2395-11e8-9270-ee1bfcfd80fa.png)

**Comment by andrewm4894** [comment]
hmm - after reading [here](https://github.com/tensorflow/tensorflow/issues/3217) and some googling  - if i just open a new notebook in my base dir of datalab i can import it:
![image](https://user-images.githubusercontent.com/2178292/37207857-cd7f0bae-2396-11e8-8d5e-ddc2221e4167.png)

Might need to maybe change the flow of the codelab a little in some way to avoid people running into this perhaps.

**Comment by andrewm4894** [comment]
if i just make a copy of the notebook `4_preproc_tft.ipynb` in the same folder the error seems to go away. Still getting the error in the original `4_preproc_tft.ipynb` notebook but not in `4_preproc_tft.ipynb-Copy1`

![image](https://user-images.githubusercontent.com/2178292/37208032-b9350774-2397-11e8-95b3-2021c786a521.png)

**Comment by lakshmanok** [comment]
Andrew, after you do a pip install, you need to reset the session to pick up the new packages. I think when you copied over the notebook, you inadvertently started a new session and so it worked.
