### ISSUE TITLE
Decommissioned link to bigquery

### ISSUE THREAD

**Issue by iconoeugen** [GoogleCloudPlatform/training-data-analyst#1346]
The link in to the bigquery `nyc_tlc.yellow.trips` table has been decommissioned:

https://github.com/GoogleCloudPlatform/training-data-analyst/blob/876106f893df58fe41d2a30d4e229c50f2aa67c6/courses/machine_learning/deepdive2/launching_into_ml/solutions/python.BQ_explore_data.ipynb#L995

The console ui message is: `The Classic UI has been decomissioned as of October 1st.`

P.S. even the Classic UI warning message has a typo :smile:

**Comment by sidgupta234** [comment]
How to use the previous bigquery links then?
