### ISSUE TITLE
Error in notebook

### ISSUE THREAD

**Issue by pratapram** [GoogleCloudPlatform/training-data-analyst#1501]
Error in this notebook:

https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive2/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb

In the penultimate cell there are errors in the following lines:

PROJECT= # TODO: Change this to your PROJECT. 
BUCKET=${PROJECT}. <- why is this in brackets?
REGION=us-east1.  <- this should be in quotes
MODEL_NAME=taxifare
VERSION_NAME=dnn

**Comment by jpatokal** [comment]
This appears syntactically correct: the brackets guard against special characters, and quotes are not necessary when setting variable values containing dashes in bash.  Closing.
