### ISSUE TITLE
Problem creating the datalab compute engine.

### ISSUE THREAD

**Issue by lopezvit** [GoogleCloudPlatform/training-data-analyst#166]
When I execute the script in this location:
training-data-analyst/datalab/cloudshell/create_vm.sh
I get the following error:
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/google-containers/global/images/family/container-vm' was not found

**Comment by lakshmanok** [comment]
sorry, that is obsolete.  I need to remove it.   Datalab is now rolled into gcloud and available directly in CloudShell.  You don't need a script anymore.  To start datalab simply type:

datalab create mydatalabvm
