### ISSUE TITLE
How to create currConditionsTable based on sensorId dynamically?

### ISSUE THREAD

**Issue by kirantpatil** [GoogleCloudPlatform/training-data-analyst#205]
Dear Sir,

I am executing streaming process job using https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/streaming/process/sandiego/src/main/java/com/google/cloud/training/dataanalyst/sandiego/CurrentConditions.java.

I would like to create table at Bigquery dynamically per sensorId and table name with sensorId as below. I am not taking project name from options but hard-coded.

```
String sensorId = info.getSensorKey();
String currConditionsTable =  "brss-711:demos." + sensorId ;

```
The table name is defined in main function, since I want to create new table per sonsorId, I need to call the above statements from "ToBQRow" function.

Even though I made "currConditionsTable" as global variable, it is not executing and I am getting "Nullpointer exception", since variable contain "null".

Please help me to resolve the issue.

Regards,
Kiran.

**Comment by lakshmanok** [comment]
If info is this object:
   LaneInfo info = c.element();
Then, this object is created only within the PTransform code.  So, you can't do it that way.

What you want to do is to use "Dynamic Destinations".  See the example code in the documentation of the class:

https://beam.apache.org/documentation/sdks/javadoc/2.2.0/org/apache/beam/sdk/io/gcp/bigquery/DynamicDestinations.html

**Comment by kirantpatil** [comment]
Dear Sir,

Your pointer helped me to resolve the issue.

Thanks.
