### ISSUE TITLE
regarding the code sample courses/machine_learning/deepdive/03_tensorflow/e_cloudmle.ipynb

### ISSUE THREAD

**Issue by netskink** [GoogleCloudPlatform/training-data-analyst#224]
In the decode_csv() function, it has

`features = dict(zip(CSV_COLUMNS, columns)` 

and CSV_COLUMNS includes the `key` column but it does not do:

features.pop('key')

Although `key' is listed as one of the columns in the CSV, shouldn't this column be dropped prior to assigning to the feature set?  

Also, this routine prints this message when doing training.  Is this a problem?

```
INFO:tensorflow:'serving_default' : Regression input must be a single string Tensor; got {'passengers': <tf.Tensor 'Placeholder_4:0' shape=(?,) dtype=float32>, 'pickuplon': <tf.Tensor 'Placeholder:0' shape=(?,) dtype=float32>, 'dropofflon': <tf.Tensor 'Placeholder_3:0' shape=(?,) dtype=float32>, 'pickuplat': <tf.Tensor 'Placeholder_1:0' shape=(?,) dtype=float32>, 'dropofflat': <tf.Tensor 'Placeholder_2:0' shape=(?,) dtype=float32>}
INFO:tensorflow:'regression' : Regression input must be a single string Tensor; got {'passengers': <tf.Tensor 'Placeholder_4:0' shape=(?,) dtype=float32>, 'pickuplon': <tf.Tensor 'Placeholder:0' shape=(?,) dtype=float32>, 'dropofflon': <tf.Tensor 'Placeholder_3:0' shape=(?,) dtype=float32>, 'pickuplat': <tf.Tensor 'Placeholder_1:0' shape=(?,) dtype=float32>, 'dropofflat': <tf.Tensor 'Placeholder_2:0' shape=(?,) dtype=float32>}
```

**Comment by lakshmanok** [comment]
Since we don't create a tf.feature_column() with the key, the key is not used for training.  So, this is fine.

The key will be passed through unchanged during prediction though, so that it is clear which prediction corresponds to which set of inputs.

Yes, you can ignore the INFO error. Normally, tensorflow expects a tf.example, but our serving function takes JSON.

**Comment by netskink** [comment]
Hello Lak,

Many thanks.  That cleared up a bunch for me.   I appreciate your time and expertise.
