### ISSUE TITLE
GSP354 Vertex AI Challenge Lab needs updating

### ISSUE THREAD

**Issue by macribas** [GoogleCloudPlatform/training-data-analyst#2248]
The [Vertex AI Challenge Lab](https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/quests/vertex-ai/vertex-challenge-lab) is broken

The associated Qwiklab ([GSP354](https://www.cloudskillsboost.google/focuses/22019?parent=catalog)) was taken offline because of that.

The notebook is using outdated versions of python libraries and docker images. Because of that the pipelines fail. 

I was able to make it work by making the appropriate changes. I'll submit a PR with those.

**Comment by JonathanTSilva** [comment]
Hello @macribas. I'm having the same problem with the lab and it's not offline yet. Do you have any updates on it?

**Comment by macribas** [comment]
> Hello @macribas. I'm having the same problem with the lab and it's not offline yet. Do you have any updates on it?

The sample code has been updated, and the lab has been fixed and tested. What error are you getting?

**Comment by VivianWen97** [comment]
Hello @macribas @JonathanTSilva, I'm having similar issues, I got pip3 not found in building the docker image.

**Comment by macribas** [comment]
@VivianWen97 and @JonathanTSilva 
Where are you running it? Can you please confirm you're having the issue when running Qwiklabs? We haven't got any tickets on it. If so please open a ticket through Qwiklabs.
This is the lab that uses this code: https://www.cloudskillsboost.google/catalog_lab/4124

**Comment by macribas** [comment]
@VivianWen97 and @JonathanTSilva an update: I was able to verify the error you're getting, it turns out the Docker image for prediction has been updated on March 31st and it no longer has Conda installed, therefore pip3 is not present. I've updated the notebook to use the March 30th image instead of the latest and issued a Pull Request.
