### ISSUE TITLE
r'^' seems unnecessary in re.match

### ISSUE THREAD

**Issue by corytu** [GoogleCloudPlatform/training-data-analyst#225]
https://github.com/GoogleCloudPlatform/training-data-analyst/blob/10f6da37116e8afff6f10fc9f49ef77df07d45de/courses/data_analysis/lab2/python/grep.py#L21

https://github.com/GoogleCloudPlatform/training-data-analyst/blob/10f6da37116e8afff6f10fc9f49ef77df07d45de/courses/data_analysis/lab2/python/grepc.py#L20

Since `re.match()` [checks for a match only at the beginning of the string](https://docs.python.org/3/library/re.html#search-vs-match) - [regardless of mode](https://stackoverflow.com/a/180993/6666231) - I wonder whether we can get rid of `r'^'` in front of `re.escape(term)` as it will do the same, and IMHO, more readable.

Alternatively, I am also considering simply using `line.startswith(term)`, which doesn't need `re` module at all, and, again IMHO, more Pythonic and faster.

**Comment by lakshmanok** [comment]
Thanks! Didn't realize re.match() and re.search() both exist. Could you submit a pull request with line.startswith(term)?
