### ISSUE TITLE
typo: BigQuery ML notebook

### ISSUE THREAD

**Issue by r-matsuzaka** [GoogleCloudPlatform/training-data-analyst#2302]
>  It specifies a 80% train | 10% eval | 20% test split to evaluate your model's performance and generalization.

80% train | 10% eval | *10%* test split is correct.

https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/quests/vertex-ai/vertex-bqml/lab_exercise.ipynb

**Comment by iennae** [comment]
Thanks for noticing this; it's been resolved now.
