### ISSUE TITLE
Dual imports of different bigquery libraries as bq can create confusion

### ISSUE THREAD

**Issue by anshbansal** [GoogleCloudPlatform/training-data-analyst#243]
In courses/machine_learning/deepdive/02_generalization/create_datasets.ipynb there are 2 imports. One at the top

> import google.datalab.bigquery as bq

and second at the last cell

> import datalab.bigquery as bq

The problem with this is that the first one uses standard sql by default and second one uses legacy sql by default. If someone runs through the whole notebook and then tries to run earlier queries then it won't work and fail with errors related to enabling standard sql.

**Comment by lakshmanok** [comment]
Thanks! could you fix and submit a PR?
