### ISSUE TITLE
San Diego Traffic Example: What is the role of LaneInfo.Java?  help wanted

### ISSUE THREAD

**Issue by erick45ar** [GoogleCloudPlatform/training-data-analyst#266]
Hi, 
I am currently learning GCP, and I've been following some of the examples in codelabs. To be more specific, I've been studying the San Diego traffic example. I don't quite understand what's the role of the file "LaneInfo.Java". It seems that these files define the input variables as strings, and then Currentconditions.java and AverageSpeeds.java use those variable definitions? As part of my learning, I am trying to replicate the same process using the Chicago Traffic dataset, but I keep running into issues when running the averagespeeds.java & laneinfo.java. Any type of insight(s) would be helpful. I am still very new to GCP and java/apache beam in general.

**Comment by lakshmanok** [comment]
Please post this in the Coursera community forum
