### ISSUE TITLE
failure with feat engineering notebook when using model trained in cloud.

### ISSUE THREAD

**Issue by netskink** [GoogleCloudPlatform/training-data-analyst#272]
@alexhanna @lakshmanok Notice the /tmp/test.json works for the locally trained model but not the cloud trained model.  Once the additional features are added the cloud version can do a predict.

[taxi-feateng.pdf](https://github.com/GoogleCloudPlatform/training-data-analyst/files/2380893/taxi-feateng.pdf)

**Comment by lakshmanok** [comment]
Fixed in this commit: https://github.com/GoogleCloudPlatform/training-data-analyst/commit/2841d96cab5d7df36d870bb21dd94d29770aace0

**Comment by netskink** [comment]
That indeed works.  Many thanks!  I am able to predict locally and with cloud trained model.  I appreciate the help folks.
