### ISSUE TITLE
Error while running python transform.py

### ISSUE THREAD

**Issue by Jayateerthrk** [GoogleCloudPlatform/training-data-analyst#274]
While running python transform.py in SSH, getting the below error:

Traceback (most recent call last):
  File "transform.py", line 11, in <module>
    import urllib.request, urllib.error, urllib.parse
ImportError: No module named request

Please help.

**Comment by Jayateerthrk** [comment]
Tried.
Now getting error as:
Traceback (most recent call last):
  File "transform.py", line 13, in <module>
    import numpy as np
ImportError: No module named 'numpy'

**Comment by alexhanna** [comment]
I found a fix to this but it revealed other issues. Let me get back to you in a second.

**Comment by alexhanna** [comment]
Commit #275 should have fixed this. Try recloning the repository or doing a git pull to get the most recent files.
