### ISSUE TITLE
How to predict in feateng.ipynb from csv data

### ISSUE THREAD

**Issue by axlesor** [GoogleCloudPlatform/training-data-analyst#276]
Used training-data-analyst/courses/machine_learning/feateng/feateng.ipynb
with kaggle nyc taxi fare dataset on colab. The issue I encountered is how to predict after trained model? Since I am not using GCP directly I read test data and call predict but predictions were all empty. Can you please let me know how to perform prediction? 

CSV_COLUMNS = 'key,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,dayofweek,hourofday'.split(',')
LABEL_COLUMN = 'fare_amount'

def pandas_test_input_fn(df):
    return tf.estimator.inputs.pandas_input_fn(
        x=df,
        y=None,
        batch_size=512,
        num_epochs=1,
        shuffle=False,
        queue_capacity=1000
    )
df_valid2 = pd.read_csv('mydata/valid.csv', header = None, names = CSV_COLUMNS)
predictions = estimator.predict(input_fn = pandas_test_input_fn(df_valid2))

It complains "ValueError: Feature euclidean is not in features dictionary." since that is coming from add_engineered. But confused how to process add_engineered when I feed the data thru pandas?
Seem like need to define tf.estimator.ModeKeys.EVAL but how, right?
Thanks

**Comment by lakshmanok** [comment]
You would need to take your pandas dataframe and call add_engineered() on every row (use df.apply(add_engineered) ) and then use the pandas input function on the resulting frame.

**Comment by axlesor** [comment]
Lakshmanok,

Thank you for the answer but not able to make it worked yet:

feature_placeholders = {
        # All the real-valued columns
        column.name: tf.placeholder(tf.float32, [None]) for column in mymodel.INPUT_COLUMNS[2:]
    }
feature_placeholders['dayofweek'] = tf.placeholder(tf.int32, [None])
feature_placeholders['hourofday'] = tf.placeholder(tf.int32, [None])

features = {
        key: tf.expand_dims(tensor, -1)
        for key, tensor in feature_placeholders.items()
    }
features:
{'dayofweek': <tf.Tensor 'ExpandDims_58:0' shape=(?, 1) dtype=int32>,
 'dropoff_latitude': <tf.Tensor 'ExpandDims_52:0' shape=(?, 1) dtype=float32>,
 'dropoff_longitude': <tf.Tensor 'ExpandDims_53:0' shape=(?, 1) dtype=float32>,
 'euclidean': <tf.Tensor 'ExpandDims_57:0' shape=(?, 1) dtype=float32>,
 'hourofday': <tf.Tensor 'ExpandDims_59:0' shape=(?, 1) dtype=int32>,
 'latdiff': <tf.Tensor 'ExpandDims_55:0' shape=(?, 1) dtype=float32>,
 'londiff': <tf.Tensor 'ExpandDims_56:0' shape=(?, 1) dtype=float32>,
 'passenger_count': <tf.Tensor 'ExpandDims_54:0' shape=(?, 1) dtype=float32>,
 'pickup_latitude': <tf.Tensor 'ExpandDims_50:0' shape=(?, 1) dtype=float32>,
 'pickup_longitude': <tf.Tensor 'ExpandDims_51:0' shape=(?, 1) dtype=float32>}

However when apply add_engneeered to frame:
df_valid2.apply(mymodel.add_engineered(features))

reachs maximum recursion and giving all sorts errors!
Any ideas what I am doing wrong?
On contrary I do add_engineered(df_valid2), then predictions all empty (which kind of makes sense).

Thanks

**Comment by axlesor** [comment]
Added axis=1 but still not working:
TypeError                                 Traceback (most recent call last)
<ipython-input-35-28d4fa2ea4cb> in <module>()
     11     }
     12 features
---> 13 df_valid2.apply(mymodel.add_engineered(features), axis=1)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, args, **kwds)
   4875                         f, axis,
   4876                         reduce=reduce,
-> 4877                         ignore_failures=ignore_failures)
   4878             else:
   4879                 return self._apply_broadcast(f, axis)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in _apply_standard(self, func, axis, ignore_failures, reduce)
   4971             try:
   4972                 for i, v in enumerate(series_gen):
-> 4973                     results[i] = func(v)
   4974                     keys.append(v.name)
   4975             except Exception as e:

TypeError: ("'dict' object is not callable", 'occurred at index 0')

**Comment by axlesor** [comment]
seem works like this:
prediction = model.predict(pandas_test_input_fn(df_valid2.apply(mymodel.add_engineered, axis=1)))

# But cannot put it into Frame yet?
#prediction_df = pd.DataFrame(prediction)

But prediction is a generator, can you please tell me how I can put it into DataFrame?
next(prediction)NFO:tensorflow:Calling model_fn.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./mytrain/model.ckpt-105000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, Unable to get element as bytes.

NFO:tensorflow:Calling model_fn.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./mytrain/model.ckpt-105000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, Unable to get element as bytes.

**Comment by axlesor** [comment]
FYI: once I replaced tf .sqrtcall in euclidean inside add_engineered, then all works fine:
141,142c141,142
-     #dist = tf.sqrt(latdiff * latdiff + londiff * londiff)
+     features['euclidean'] = (latdiff * latdiff + londiff * londiff)**0.5

**Comment by rafiqhasan** [comment]
Ideally, the right way to do this is via TF functions only as you wont be able to deploy a pipeline with Panda's functions. For example, to do complex feature engineering steps using Pandas.apply() method in add_engineered() method is not an option.

So, the only way there is using TF based transformations or functions, hence the example above has tf.sqrt.

Hence for real world model, you should consider re-writing your pipeline with the **decode_csv** function rather than using the **pandas input** method.

**Comment by axlesor** [comment]
RafidHasan thanks for your comment.
