### ISSUE TITLE
train_and_evaluate does not seem to work for me

### ISSUE THREAD

**Issue by omonfared** [GoogleCloudPlatform/training-data-analyst#281]
Hi,

I was running this code on GCP and  when I get to this line of code, it ended up in an error

train_and_evaluate('babyweight_trained')

I checked every single line of code in the training section and it seems like the error is from the line I mentioned.

InvalidArgumentErrorTraceback (most recent call last)
<ipython-input-50-4e8d63660ec4> in <module>()
     26 
     27 shutil.rmtree('babyweight_trained', ignore_errors=True) # start fresh each time
---> 28 train_and_evaluate('babyweight_trained')

<ipython-input-50-4e8d63660ec4> in train_and_evaluate(output_dir)
     23                          steps=None,
     24                          exporters=exporter)
---> 25     tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
     26 
     27 shutil.rmtree('babyweight_trained', ignore_errors=True) # start fresh each time

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/training.pyc in train_and_evaluate(estimator, train_spec, eval_spec)
    437         '(with task id 0).  Given task id {}'.format(config.task_id))
    438 
--> 439   executor.run()
    440 
    441 

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/training.pyc in run(self)
    516         config.task_type != run_config_lib.TaskType.EVALUATOR):
    517       logging.info('Running training and evaluation locally (non-distributed).')
--> 518       self.run_local()
    519       return
    520 

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/training.pyc in run_local(self)
    648           input_fn=self._train_spec.input_fn,
    649           max_steps=self._train_spec.max_steps,
--> 650           hooks=train_hooks)
    651 
    652       # Final export signal: For any eval result with global_step >= train

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.pyc in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    361 
    362     saving_listeners = _check_listeners_type(saving_listeners)
--> 363     loss = self._train_model(input_fn, hooks, saving_listeners)
    364     logging.info('Loss for final step: %s.', loss)
    365     return self

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.pyc in _train_model(self, input_fn, hooks, saving_listeners)
    841       return self._train_model_distributed(input_fn, hooks, saving_listeners)
    842     else:
--> 843       return self._train_model_default(input_fn, hooks, saving_listeners)
    844 
    845   def _train_model_default(self, input_fn, hooks, saving_listeners):

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.pyc in _train_model_default(self, input_fn, hooks, saving_listeners)
    857       return self._train_with_estimator_spec(estimator_spec, worker_hooks,
    858                                              hooks, global_step_tensor,
--> 859                                              saving_listeners)
    860 
    861   def _train_model_distributed(self, input_fn, hooks, saving_listeners):

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.pyc in _train_with_estimator_spec(self, estimator_spec, worker_hooks, hooks, global_step_tensor, saving_listeners)
   1057       loss = None
   1058       while not mon_sess.should_stop():
-> 1059         _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
   1060     return loss
   1061 

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.pyc in __exit__(self, exception_type, exception_value, traceback)
    677     if exception_type in [errors.OutOfRangeError, StopIteration]:
    678       exception_type = None
--> 679     self._close_internal(exception_type)
    680     # __exit__ should return True to suppress an exception.
    681     return exception_type is None

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.pyc in _close_internal(self, exception_type)
    714         if self._sess is None:
    715           raise RuntimeError('Session is already closed.')
--> 716         self._sess.close()
    717       finally:
    718         self._sess = None

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.pyc in close(self)
    962     if self._sess:
    963       try:
--> 964         self._sess.close()
    965       except _PREEMPTION_ERRORS:
    966         pass

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.pyc in close(self)
   1106       self._coord.join(
   1107           stop_grace_period_secs=self._stop_grace_period_secs,
-> 1108           ignore_live_threads=True)
   1109     finally:
   1110       try:

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/coordinator.pyc in join(self, threads, stop_grace_period_secs, ignore_live_threads)
    387       self._registered_threads = set()
    388       if self._exc_info_to_raise:
--> 389         six.reraise(*self._exc_info_to_raise)
    390       elif stragglers:
    391         if ignore_live_threads:

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.pyc in _run(self, sess, enqueue_op, coord)
    250           break
    251         try:
--> 252           enqueue_callable()
    253         except self._queue_closed_exception_types:  # pylint: disable=catching-non-exception
    254           # This exception indicates that a queue was closed.

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _single_operation_run()
   1242 
   1243       def _single_operation_run():
-> 1244         self._call_tf_sessionrun(None, {}, [], target_list, None)
   1245 
   1246       return _single_operation_run

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1407       return tf_session.TF_SessionRun_wrapper(
   1408           self._session, options, feed_dict, fetch_list, target_list,
-> 1409           run_metadata)
   1410     else:
   1411       with errors.raise_exception_on_not_ok_status() as status:

InvalidArgumentError: assertion failed: [string_input_producer requires a non-null input tensor]
	 [[Node: input_producer/Assert/Assert = Assert[T=[DT_STRING], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_producer/Greater, input_producer/Assert/Assert/data_0)]]

InvalidArgumentErrorTraceback (most recent call last)
<ipython-input-50-4e8d63660ec4> in <module>()
     26 
     27 shutil.rmtree('babyweight_trained', ignore_errors=True) # start fresh each time
---> 28 train_and_evaluate('babyweight_trained')

<ipython-input-50-4e8d63660ec4> in train_and_evaluate(output_dir)
     23                          steps=None,
     24                          exporters=exporter)
---> 25     tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
     26 
     27 shutil.rmtree('babyweight_trained', ignore_errors=True) # start fresh each time

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/training.pyc in train_and_evaluate(estimator, train_spec, eval_spec)
    437         '(with task id 0).  Given task id {}'.format(config.task_id))
    438 
--> 439   executor.run()
    440 
    441 

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/training.pyc in run(self)
    516         config.task_type != run_config_lib.TaskType.EVALUATOR):
    517       logging.info('Running training and evaluation locally (non-distributed).')
--> 518       self.run_local()
    519       return
    520 

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/training.pyc in run_local(self)
    648           input_fn=self._train_spec.input_fn,
    649           max_steps=self._train_spec.max_steps,
--> 650           hooks=train_hooks)
    651 
    652       # Final export signal: For any eval result with global_step >= train

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.pyc in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    361 
    362     saving_listeners = _check_listeners_type(saving_listeners)
--> 363     loss = self._train_model(input_fn, hooks, saving_listeners)
    364     logging.info('Loss for final step: %s.', loss)
    365     return self

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.pyc in _train_model(self, input_fn, hooks, saving_listeners)
    841       return self._train_model_distributed(input_fn, hooks, saving_listeners)
    842     else:
--> 843       return self._train_model_default(input_fn, hooks, saving_listeners)
    844 
    845   def _train_model_default(self, input_fn, hooks, saving_listeners):

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.pyc in _train_model_default(self, input_fn, hooks, saving_listeners)
    857       return self._train_with_estimator_spec(estimator_spec, worker_hooks,
    858                                              hooks, global_step_tensor,
--> 859                                              saving_listeners)
    860 
    861   def _train_model_distributed(self, input_fn, hooks, saving_listeners):

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.pyc in _train_with_estimator_spec(self, estimator_spec, worker_hooks, hooks, global_step_tensor, saving_listeners)
   1057       loss = None
   1058       while not mon_sess.should_stop():
-> 1059         _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
   1060     return loss
   1061 

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.pyc in __exit__(self, exception_type, exception_value, traceback)
    677     if exception_type in [errors.OutOfRangeError, StopIteration]:
    678       exception_type = None
--> 679     self._close_internal(exception_type)
    680     # __exit__ should return True to suppress an exception.
    681     return exception_type is None

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.pyc in _close_internal(self, exception_type)
    714         if self._sess is None:
    715           raise RuntimeError('Session is already closed.')
--> 716         self._sess.close()
    717       finally:
    718         self._sess = None

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.pyc in close(self)
    962     if self._sess:
    963       try:
--> 964         self._sess.close()
    965       except _PREEMPTION_ERRORS:
    966         pass

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.pyc in close(self)
   1106       self._coord.join(
   1107           stop_grace_period_secs=self._stop_grace_period_secs,
-> 1108           ignore_live_threads=True)
   1109     finally:
   1110       try:

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/coordinator.pyc in join(self, threads, stop_grace_period_secs, ignore_live_threads)
    387       self._registered_threads = set()
    388       if self._exc_info_to_raise:
--> 389         six.reraise(*self._exc_info_to_raise)
    390       elif stragglers:
    391         if ignore_live_threads:

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.pyc in _run(self, sess, enqueue_op, coord)
    250           break
    251         try:
--> 252           enqueue_callable()
    253         except self._queue_closed_exception_types:  # pylint: disable=catching-non-exception
    254           # This exception indicates that a queue was closed.

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _single_operation_run()
   1242 
   1243       def _single_operation_run():
-> 1244         self._call_tf_sessionrun(None, {}, [], target_list, None)
   1245 
   1246       return _single_operation_run

/usr/local/envs/py2env/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1407       return tf_session.TF_SessionRun_wrapper(
   1408           self._session, options, feed_dict, fetch_list, target_list,
-> 1409           run_metadata)
   1410     else:
   1411       with errors.raise_exception_on_not_ok_status() as status:

InvalidArgumentError: assertion failed: [string_input_producer requires a non-null input tensor]
	 [[Node: input_producer/Assert/Assert = Assert[T=[DT_STRING], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_producer/Greater, input_producer/Assert/Assert/data_0)]]

**Comment by lakshmanok** [comment]
Looks like the input directory is empty or otherwise invalid
