### ISSUE TITLE
Small typo in compose_gcf_trigger lab

### ISSUE THREAD

**Issue by akreuzer** [GoogleCloudPlatform/training-data-analyst#334]
In the jupyter notebook ```courses/machine_learning/deepdive/10_recommend/composer_gcf_trigger/composertriggered.ipynb```
there is a typo/inconsistency in the name of the airflow-variable `gcp_completion_bucket`.
In the section __Complete the DAG file__ it is called `gcs_completion_bucket` (note the **s** at third position).
However, in the section __Setting Airflow variables__ it is called `gcp_completion_bucket`. (I guess this name is correct since it conforms with the names of the other variables.)

The same applies to the the jupyter notebook in the `labs` folder ```courses/machine_learning/deepdive/10_recommend/labs/composer_gcf_trigger/composertriggered.ipynb```

**Comment by jonesevan** [comment]
Thanks - fixed in #335 

Do let me know if there is other feedback on that lab or the other Cloud Composer one

**Comment by akreuzer** [comment]
> Do let me know if there is other feedback on that lab or the other Cloud Composer one

Yes, there is another small thing. For the `labs` version of the endtoend lab (so `courses/machine_learning/deepdive/10_recommend/labs/endtoend/endtoend.ipynb`)
 the patch from #321 would also have to be applied.

**Comment by alexhanna** [comment]
Fixed in https://github.com/GoogleCloudPlatform/training-data-analyst/commit/f0d8b902492ebb46ccfe933bbe9af3d79290a234
