### ISSUE TITLE
No module named sklearn_crfsuite.estimator

### ISSUE THREAD

**Issue by jeffersonramoslucas** [GoogleCloudPlatform/training-data-analyst#338]
I using sklearn_crfsuite estimator

crf = sklearn_crfsuite.CRF(
        algorithm='lbfgs',
        c1=0.1,
        c2=0.1,
        max_iterations=2,
        all_possible_transitions=True
    )

I'm saving the model as described below:

model = 'model.joblib'
joblib.dump(crf, model)

and when I try to deploy the model it reports this error:

ERROR: (gcloud.alpha.ml-engine.versions.create) Bad model detected with error:  "Failed to load model: Could not load the model: /tmp/model/0001/model.joblib. No module named sklearn_crfsuite.estimator. (Error code: 0)"

deploy model:
gcloud alpha ml-engine versions create v1 --model teste --origin $ORI --python-version 2.7 --runtime-version 1.8  --framework scikit-learn

**Comment by alexhanna** [comment]
What lab is this in?

**Comment by jeffersonramoslucas** [comment]
This error occurs if I change the estimator to sklearn_crfsuite.crf instead of RandomForestRegressor

lab babyweight_skl.ipynb

**Comment by alexhanna** [comment]
I'm assuming this has to do with your sklearn_crfsuite install, rather than with gcloud.
