### ISSUE TITLE
Permission denied on resource project

### ISSUE THREAD

**Issue by AlbinB** [GoogleCloudPlatform/training-data-analyst#348]
When running b_hyperparam.ipynb from 
datalab/notebooks/training-data-analyst/courses/machine_learning/deepdive/05_artandscience/labs
or 
datalab/notebooks/training-data-analyst/courses/machine_learning/deepdive/05_artandscience/

I keep on getting: 
Removing gs://qwiklabs-gcp-0c3e9ec8e4427080/house_trained/packages/0a26bfb7f0d02a513fe9c410c169dd06a3a4a5c1f6fdd14ca96cc66ac17fdf17/trainer-0.0.0.tar.gz#1545415738922023...
/ [1 objects]                                                                   
Operation completed over 1 objects.                                              
ERROR: (gcloud.ml-engine.jobs.submit.training) User [974813017927-compute@developer.gserviceaccount.com] does not have permission to access project [qwiklabs-gcp-0c3e9ec8e4427080s] (or it may not exist): Permission denied on resource project qwiklabs-gcp-0c3e9ec8e4427080s.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console
    url: https://console.developers.google.com

**Comment by lakshmanok** [comment]
looks like the ml engine api is not enabled -- this might have been a qwiklabs startup error. You could stopping & restarting the lab.
