### ISSUE TITLE
Passing RNN state to next batch in customer estimator?

### ISSUE THREAD

**Issue by SinanGabel** [GoogleCloudPlatform/training-data-analyst#353]
source: https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive/05_artandscience/d_customestimator.ipynb

In model code "simple_rnn" the state is not passed on to the next batch (if I understand it correctly):

```
   outputs, _ = rnn.static_rnn(lstm_cell, x, dtype = tf.float32)
```

However if we had a very long time series (SEQ_LEN large e.g. 10000) that we would want to split up into smaller chunks how could we pass on the state to the next batch (i.e. rather than starting from a zero state each time)?

```
   # initialize somewhere
   state = tf.zeros([BATCH_SIZE, LSTM_SIZE], dtype=tf.float32)  

   # in model code
   outputs, state = rnn.static_rnn(lstm_cell, x, initial_state=state, dtype=tf.float32)

   # the outputs are passed on and used to produce the "predictions_dict"

```

QUESTION: where & how do we initialize the state, and how is the state passed on when creating a customer estimator?

**Comment by lakshmanok** [comment]
The simple_rnn illustrates the case where you have multiple independent short sequences.

For training on a single long sequence, look at the temperatures notebook in Course 9 (which is on sequences):

https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive/09_sequence/temperatures.ipynb
