### ISSUE TITLE
Serverless Machine Learning - Lab 7 : Feature Engineering v1.3: apache-beam not installed because of dill

### ISSUE THREAD

**Issue by tarrade** [GoogleCloudPlatform/training-data-analyst#383]
I have some issue with the first cell of the following notebook:
https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/feateng/feateng.ipynb

```
%%bash
conda update -y -n base -c defaults conda
source activate py2env
pip uninstall -y google-cloud-dataflow
conda install -y pytz 
pip install apache-beam[gcp]
```

It seems the issue  is the installation of apache-beam:

> ...
> Requirement already satisfied: cachetools>=2.0.0 in /usr/local/envs/py2env/lib/python2.7/site-packages (from google-auth<2.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=1.4.1->google-cloud-pubsub==0.39.0; extra == "gcp"->apache-beam[gcp]) (2.1.0)
> Installing collected packages: dill, pyarrow, typing, pyvcf, fastavro, httplib2, docopt, hdfs, grpc-google-iam-v1, google-api-core, google-cloud-pubsub, monotonic, fasteners, google-apitools, google-cloud-bigquery, apache-beam
>   Found existing installation: dill 0.2.6
> Skipping google-cloud-dataflow as it is not installed.
> google-cloud-monitoring 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.7.0 which is incompatible.
> googledatastore 7.0.1 has requirement httplib2<0.10,>=0.9.1, but you'll have httplib2 0.11.3 which is incompatible.
> Cannot uninstall 'dill'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

then if I check, I don't see the package installed:
`conda list`

the right env is activated:

> py2env                *  /usr/local/envs/py2env

so when trying to in port the package it doesn't work (restarting the kernel doesn't help since the package was not installed):

```
ImportErrorTraceback (most recent call last)
<ipython-input-4-830e0319c5fc> in <module>()
      1 import tensorflow as tf
----> 2 import apache_beam as beam
      3 import shutil
      4 print(tf.__version__)


ImportError: No module named apache_beam
```

It seems that

> !conda uninstall dill=0.2.6 -y

can drop dill and then the installation of apache-beam is working. My 1:30 min session is over. I will start again and see if this was a temporary glitch and if the solution above is working.

**Comment by tarrade** [comment]
yes, I confirm that starting the lab, I am getting the same issue and deleting dill modue using conda seems to help installing apache-beam later.

**Comment by tarrade** [comment]
there are other issues later related to some other conflict between python packages:
```
preprocess(50*100, 'DataflowRunner') 
#change first arg to None to preprocess full dataset
```

`
Launching Dataflow job preprocess-taxifeatures-190217-214012 ... hang on

ContextualVersionConflictTraceback (most recent call last)
...
ContextualVersionConflict: (httplib2 0.12.0 (/usr/local/envs/py2env/lib/python2.7/site-packages), Requirement.parse('httplib2<=0.11.3,>=0.8'), set(['apache-beam']))`

I think this is related to a Warning during the installation of some python packages:

> Skipping google-cloud-dataflow as it is not installed.
> google-cloud-monitoring 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.7.0 which is incompatible.
> googledatastore 7.0.1 has requirement httplib2<0.10,>=0.9.1, but you'll have httplib2 0.11.3 which is incompatible.

**Comment by lakshmanok** [comment]
Yes, we are aware of this issue. It is caused by the latest version of Apache Beam and we are working on a fix.  In the meantime, the fix is to:

pip install apache-beam==2.9.0

**Comment by tarrade** [comment]
Hi Lak,

thanks for the inout and good to know that you are aware of this issue.

you are right that: pip install apache-beam==2.9.0 solve the env issue but later I cannot run beam since it is crashing in both local  and distributed way.

I will try again later since every time I get some different messages. I will use my own account to be able to investigate a bit more than for 1:30.

Thanks
Cheers
Fabien

**Comment by tarrade** [comment]
Hi Lak,

I managed to find time to redo the lab and now everything is working fine with the instruction in Qwiklabs:

```
%%bash
conda update -y -n base -c defaults conda
source activate py2env
pip uninstall -y google-cloud-dataflow
conda install -y pytz 
pip install apache-beam[gcp]==2.9.0
```

Closing this ticket.
Thanks again for the great courses.
Cheers
Fabien
