### ISSUE TITLE
1_create_cluster.sh failed ("1.11.2-gke.26" is unsupported.)

### ISSUE THREAD

**Issue by myoshimu** [GoogleCloudPlatform/training-data-analyst#457]
Executing create_cluster.sh failed with following error:

ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Master version "1.11.2-gke.26" is unsupported.

Would you please modify the version appropriately?
When I removed the cluster-version option, it worked fine.

**Comment by lakshmanok** [comment]
perhaps you tried in a different zone?
added a comment to startup script

**Comment by myoshimu** [comment]
gcloud container get-server-config shows following versions so I guess we should choose one of below:

validMasterVersions:
- 1.13.6-gke.0
- 1.13.5-gke.10
- 1.12.7-gke.17
- 1.12.7-gke.10
- 1.12.6-gke.11
- 1.11.9-gke.13
- 1.11.9-gke.8
- 1.11.8-gke.6

**Comment by myoshimu** [comment]
Sorry, I was seeing us-central1-b instead of a. Closing this issue.
