### ISSUE TITLE
as

### ISSUE THREAD

**Issue by crawles** [GoogleCloudPlatform/training-data-analyst#602]
![image](https://user-images.githubusercontent.com/5091145/66138946-868db100-e5cd-11e9-9a8c-95470e537945.png)

need to add `GROUP BY userId, movieId, rating` add the bottom

**Comment by danideter** [comment]
Good call using the issue feature of github, Chris. I'll give it a shot :)

**Comment by crawles** [comment]
Thanks Danielle. Sorry think I need help from you on using github otherwise would have done it myself. Found one other bug :)

![image](https://user-images.githubusercontent.com/5091145/66233579-b74b1480-e6b9-11e9-98d1-1d82230ad26f.png)

add the highlighted part

**Comment by danideter** [comment]
No need to apologize, Chris :)
Hmmm, I noticed that the duplicate entries occur if the data creation cell is ran multiple times. I added code to delete and then create the movielens dataset because GROUP BY is a time expensive operation.

**Comment by jonesevan** [comment]
Nice fix

**Comment by danideter** [comment]
Branched merged. Please reopen if there are any issues.
