### ISSUE TITLE
Number of samples not getting matched in TPU distribution strategy

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/training-data-analyst#678]
Hi @martin-gorner. I am following your notebook [keras_flowers_gputputpupod_tf2.1.ipynb](https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/fast-and-lean-data-science/keras_flowers_gputputpupod_tf2.1.ipynb). I was able to follow through this example pretty smoothly and thank you for putting it together and sharing it :)

I wanted to try it on a pet project I was working on. I first defined the strategy (after all the initial configuration on GCP):

```python
# Detect hardware, return appropriate distribution strategy
try:
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
    print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
except ValueError:
    tpu = None

if tpu:
    tf.config.experimental_connect_to_cluster(tpu)
    tf.tpu.experimental.initialize_tpu_system(tpu)
    strategy = tf.distribute.experimental.TPUStrategy(tpu)
else:
    strategy = tf.distribute.get_strategy()

print("REPLICAS: ", strategy.num_replicas_in_sync)
```

You can verify the output in the following as well:

![image](https://user-images.githubusercontent.com/22957388/67966877-a5ae4b80-fc2a-11e9-8745-cce24097fb7f.png)

My training data in the form of `numpy` array and after compiling in the way you had shown in the notebook, I am calling `fit` on the compiled model:

```python
compiled_model.fit(train_features, y_train_binarized,
                        class_weight=class_weight,
                        steps_per_epoch=len(train_features)//8 * strategy.num_replicas_in_sync,
                        epochs=15,
                        batch_size=8 * strategy.num_replicas_in_sync,
                        validation_split=0.1)
```

The shape of `traini_features` is `(26152, 300)` and the model's input is defined accordingly. When the above is run, it gives me:

```
ValueError                                Traceback (most recent call last)
<ipython-input-29-61629493fd70> in <module>
      4                         epochs=15,
      5                         batch_size=8 * strategy.num_replicas_in_sync,
----> 6                         validation_split=0.1)

/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    783         max_queue_size=max_queue_size,
    784         workers=workers,
--> 785         use_multiprocessing=use_multiprocessing)
    786 
    787   def evaluate(self,

/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    210         steps_per_epoch,
    211         ModeKeys.TRAIN,
--> 212         validation_split=validation_split)
    213     dist_utils.validate_callbacks(input_callbacks=callbacks,
    214                                   optimizer=model.optimizer)

/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py in process_batch_and_step_size(strategy, inputs, batch_size, steps_per_epoch, mode, validation_split)
    467     # relax the constraint to consume all the training samples.
    468     steps_per_epoch, batch_size = get_input_params(
--> 469         strategy, num_samples, steps_per_epoch, batch_size, mode=mode)
    470   return batch_size, steps_per_epoch
    471 

/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py in get_input_params(distribution_strategy, num_samples, steps, batch_size, mode)
    559         raise ValueError('Number of samples %s is less than samples required '
    560                          'for specified batch_size %s and steps %s' % (
--> 561                              num_samples, global_batch_size, steps))
    562 
    563   # We need to return the per replica or global batch size based on the strategy

ValueError: Number of samples 23536 is less than samples required for specified batch_size 64 and steps 408
```

The number of samples in the above log is different from the original and I am not able to figure out why. You can find the files here in order to reproduce the issue:

[Archive.zip](https://github.com/GoogleCloudPlatform/training-data-analyst/files/3794936/Archive.zip)

**Comment by martin-gorner** [comment]
I do not know exactly what is going on but I would advise you to use a repeating dataset (dataset.repeat()) for your training data and a separate dataset for validation (without .repeat or valid_steps). We might have to test more with validation_split

**Comment by sayakpaul** [comment]
Cool. I will try that out. Just so you know, `train_features` and `y_train_binarized` and numpy arrays.

**Comment by martin-gorner** [comment]
model.fit() works with numpy arrays on TPUs.
The error probably means that you do not have enough data in the numpy array for one epoch.
You can also try to remove steps_per_epoch and it will use the entire numpy array as one epoch.

**Comment by martin-gorner** [comment]
After recounting your data elements, batches, steps, etc, can you please tell me if the error message is accurate or if you still think there is a bug ?

Also, could you please copy-paste the TF version you tried this on:
print("Tensorflow version " + tf.__version__)

**Comment by sayakpaul** [comment]
Oh yes! I got it to up and running just now. The problem was indeed in `validation_split`. When you specify the training data to be `train_features` and `y_train_binarized` and at the same time you also specify `validation_split` the different cores of the respective Cloud TPU fail to handle it properly, just like you hinted. 

So, I modified the `fit` function like so:

```python
compiled_model.fit(train_features, y_train_binarized,
                        class_weight=class_weight,
                        steps_per_epoch=len(train_features)//(8 * strategy.num_replicas_in_sync),
                        validation_data=(test_features, y_test_binarized),
                        validation_steps=len(test_features)//(8 * strategy.num_replicas_in_sync),
                        epochs=15,
                        batch_size=8 * strategy.num_replicas_in_sync)
```

Now it was running in its full glory and the speed was _blazing fast_. Regarding the following:

> Also, could you please copy-paste the TF version you tried this on:
print("Tensorflow version " + tf.version)

It's `2.1.0-dev20191029`. I think the logging could have been changed a bit:

```
Train on 26152 samples, validate on 6538 samples
Epoch 1/15
26112/26152 [============================>.] - ETA: 0s - loss: 0.2301 - categorical_accuracy: 0.2482 - val_loss: 0.1260 - val_categorical_accuracy: 0.3073Epoch 2/15
26088/26152 [============================>.] - ETA: 0s - loss: 0.1229 - categorical_accuracy: 0.3073 - val_loss: 0.1210 - val_categorical_accuracy: 0.3073Epoch 3/15
```

There is no information on the time it took to complete that epoch or how much time it took per step. Is it normal? 

I ran the same version on my V100 GCP instance and the performance was _better_ (although the training time was significantly higher). I am also leaving you the notebook for your perusal. 

[notebook.ipynb.zip](https://github.com/GoogleCloudPlatform/training-data-analyst/files/3796654/notebook.ipynb.zip)

**Comment by martin-gorner** [comment]
> V100 GCP instance and the performance was better (although the training time was significantly higher)

Yes, if you are training with larger batches, you should also increase your learning rate. In theory you scale your learning rate by strategy.num_replicas_in_sync. In practice, finding the learning rate schedule that works with bigger and bigger batches might be a bit more involved. You might want to add LR decay, and with even bigger batches (32 or 128 core pods) I found that adding a couple of rampup epochs at the beginning can sometimes help.

Thanks for the bug report. I passed it on to the TF team.
I was not able to run your notebook though. There is a missing import (import utils as utils) and I do not have your data. Would you be able to add that in your zip ? (even a partial dataset)

**Comment by martin-gorner** [comment]
Hi Paul

I think I understand the error you got and it seems correct to me:

Your dataset has 26152 elements.
You use a validation_split of .1 so your training dataset has 23536 elements.
But you also specify
steps_per_epoch=len(train_features)//8 * strategy.num_replicas_in_sync
which I believe is not correct.

The easiest way to fix it is to remove steps_per_epochs entirely. You will lose the progress bar on the first epoch but for the second epoch, keras should remember how many elements it saw in an epoch and display a correct progress bar.

If you want to keep steps_per_epoch, I think it should be:
train_elements = int(len(train_features)*(1-0.1))
steps_per_epoch= train_elements//(8 * strategy.num_replicas_in_sync)

**Comment by sayakpaul** [comment]
@martin-gorner thank you very much for your detailed insights regarding adjusting the learning rate. They would really be helpful. Would you mind if I added those notes in the notebook with credits? 

Regarding `validation_split` error, I think you missed the point I had made in my previous comment:

> The problem was indeed in validation_split. When you specify the training data to be train_features and y_train_binarized and at the same time you also specify validation_split the different cores of the respective Cloud TPU fail to handle it properly, just like you hinted.

I initially tried without `steps_per_epoch` actually and it was giving me a `Not Divisible Error`. 

Also, here's the notebook (the working one) again with the necessary files including the dataset: 
[Archive.zip](https://github.com/GoogleCloudPlatform/training-data-analyst/files/3800129/Archive.zip)

**Comment by martin-gorner** [comment]
My point was that the TPU should handle validation_split properly, but you must supply enough data for one training epoch. i.e. batch_size * steps_per_epoch must be <= nb data elements * (1- validation_split)

I think that in your case, you assumed the number of data elements available for training was len(train_features) when in fact it is len(train_features)-(1-validation_split)

**Comment by sayakpaul** [comment]
> I think that in your case, you assumed the number of data elements available for training was len(train_features) when in fact it is len(train_features)-(1-validation_split)

Correct, @martin-gorner. Thanks for pointing that out.
