### ISSUE TITLE
imports don't work anymore

### ISSUE THREAD

**Issue by Afif00** [GoogleCloudPlatform/training-data-analyst#696]
> ERROR: Could not find a version that satisfies the requirement apache-beam[gcp]==2.9.0 (from versions: 0.6.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.16.0)
> ERROR: No matching distribution found for apache-beam[gcp]==2.9.0

**Comment by lakshmanok** [comment]
Which notebook or file?

**Comment by Afif00** [comment]
two of them didn't work for me, tftransform.ipynb and training-data-analyst > courses > machine_learning > deepdive > 04_features > taxifeateng and open feateng.ipynb
They're both in the feature engineering course, when using beam
ps -- thanks for the course!

**Comment by lakshmanok** [comment]
Thanks, should be 2.16.  I'll update
