### ISSUE TITLE
Facing issue while consuming datastore from the qwiklabs

### ISSUE THREAD

**Issue by SriramUmapathy** [GoogleCloudPlatform/training-data-analyst#871]
5 NOT_FOUND: The project DEVSHELL_PROJECT_ID does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=DEVSHELL_PROJECT_ID to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled.

https://googlepluralsight.qwiklabs.com/focuses/38994

**Comment by lakshmanok** [comment]
You are missing a $ (dollar sign) in whatever command you are using.

**Comment by SriramUmapathy** [comment]
Hi @lakshmanok thank you for your response, fixed now.
